import { execSync } from 'node:child_process'
import { writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

import { getTableColumns, getTableName, is } from 'drizzle-orm'
import { SQLiteTable } from 'drizzle-orm/sqlite-core'
import { generateDrizzleJson } from 'drizzle-kit/api'

import * as clientSchema from '@/data/client/db-schema'
import * as serverSchema from '@/data/server/db-schema'

interface SnapshotForeignKey {
  tableFrom: string
  tableTo: string
  columnsFrom: string[]
  columnsTo: string[]
  onDelete: string
}

interface SnapshotTable {
  name: string
  foreignKeys?: Record<string, SnapshotForeignKey>
}

interface RawCascadeEdge {
  child: string
  childCol: string
  parent: string
  parentCol: string
}

const clientTablesByName = new Map<string, SQLiteTable>()
const clientVarByTableName = new Map<string, string>()
for (const [key, value] of Object.entries(clientSchema)) {
  if (!is(value, SQLiteTable)) continue
  const table = value as SQLiteTable
  clientTablesByName.set(getTableName(table), table)
  clientVarByTableName.set(getTableName(table), key)
}

const snapshot = generateDrizzleJson(serverSchema)
const edges: RawCascadeEdge[] = []
for (const tableData of Object.values(snapshot.tables)) {
  const table = tableData as SnapshotTable
  for (const fk of Object.values(table.foreignKeys ?? {})) {
    if (fk.onDelete !== 'cascade') continue
    if (!clientTablesByName.has(fk.tableFrom)) continue
    if (!clientTablesByName.has(fk.tableTo)) continue
    edges.push({
      child: fk.tableFrom,
      childCol: fk.columnsFrom[0],
      parent: fk.tableTo,
      parentCol: fk.columnsTo[0]
    })
  }
}
edges.sort((a, b) =>
  `${a.child}.${a.childCol}->${a.parent}.${a.parentCol}`.localeCompare(
    `${b.child}.${b.childCol}->${b.parent}.${b.parentCol}`
  )
)

function columnCamelKey(table: SQLiteTable, sqlName: string): string {
  for (const [camelKey, col] of Object.entries(getTableColumns(table))) {
    if (col.name === sqlName) return camelKey
  }
  throw new Error(
    `Column ${sqlName} not found on client table ${getTableName(table)}`
  )
}

const referenced = new Set<string>()
for (const e of edges) {
  referenced.add(e.parent)
  referenced.add(e.child)
}
const importNames = [...referenced]
  .map(n => clientVarByTableName.get(n))
  .filter((n): n is string => Boolean(n))
  .sort()

const lines: string[] = []
lines.push(
  '// GENERATED by scripts/generate-cascade-edges.ts. Do not edit. Run `bun run gen:cascade-edges`.'
)
lines.push('')
lines.push(
  `import { ${importNames.join(', ')} } from '@/data/client/db-schema'`
)
lines.push('')
lines.push("import type { CascadeEdge } from './cascade-edges-type'")
lines.push('')
lines.push('export const CASCADE_EDGES: readonly CascadeEdge[] = [')

for (const e of edges) {
  const parentVar = clientVarByTableName.get(e.parent)!
  const childVar = clientVarByTableName.get(e.child)!
  const parentTable = clientTablesByName.get(e.parent)!
  const childTable = clientTablesByName.get(e.child)!
  const parentKey = columnCamelKey(parentTable, e.parentCol)
  const childFk = columnCamelKey(childTable, e.childCol)
  lines.push('  {')
  lines.push(`    parent: ${parentVar},`)
  lines.push(`    child: ${childVar},`)
  lines.push(`    parentKey: ${parentVar}.${parentKey},`)
  lines.push(`    childFk: ${childVar}.${childFk}`)
  lines.push('  },')
}

lines.push(']')
lines.push('')

const outPath = resolve(
  import.meta.dirname,
  '../src/data/client/mutations/cascade-edges.generated.ts'
)
writeFileSync(outPath, lines.join('\n'))
execSync(`bunx prettier --write "${outPath}"`, { stdio: 'inherit' })
